### ISSUE TITLE
Crashes when moving slider in peace of mind

### ISSUE THREAD

**Issue by dalb8** [Kwamecorp/Fairphone#11] opened 2014-01-09 19:52 UTC
```
D/PeaceOfMindActivity(18537): Index: 0 - 0
D/PeaceOfMindActivity(18537): Index: 4 - 60000
D/PeaceOfMindActivity(18537): Index: 1 - -60000
D/PeaceOfMindActivity(18537): Index: 7 - -120000
D/PeaceOfMindActivity(18537): Index: 6 - -60000
D/PeaceOfMindActivity(18537): Index: 1 - -60000
D/PeaceOfMindActivity(18537): Index: 3 - 120000
D/PeaceOfMindActivity(18537): Index: 8 - 120000
D/PeaceOfMindActivity(18537): Index: 0 - 0
D/PeaceOfMindActivity(18537): Index: 4 - 60000
D/PeaceOfMindActivity(18537): Index: 5 - 0
D/PeaceOfMindActivity(18537): Index: 7 - -120000
D/PeaceOfMindActivity(18537): Index: 9 - 60000
D/PeaceOfMindActivity(18537): Index: 9 - 60000
D/PeaceOfMindActivity(18537): Index: 9 - 60000
E/DatabaseUtils(  386): Writing exception to parcel
E/DatabaseUtils(  386): java.lang.SecurityException: Permission denial: writing to secure settings requires android.permission.WRITE_SECURE_SETTINGS
E/DatabaseUtils(  386):     at com.android.providers.settings.SettingsProvider.checkWritePermissions(SettingsProvider.java:275)
E/DatabaseUtils(  386):     at com.android.providers.settings.SettingsProvider.insertForUser(SettingsProvider.java:866)
E/DatabaseUtils(  386):     at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:603)
E/DatabaseUtils(  386):     at android.content.ContentProvider$Transport.call(ContentProvider.java:256)
E/DatabaseUtils(  386):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:256)
E/DatabaseUtils(  386):     at android.os.Binder.execTransact(Binder.java:351)
E/DatabaseUtils(  386):     at com.android.server.SystemServer.init1(Native Method)
E/DatabaseUtils(  386):     at com.android.server.SystemServer.main(SystemServer.java:1179)
E/DatabaseUtils(  386):     at java.lang.reflect.Method.invokeNative(Native Method)
E/DatabaseUtils(  386):     at java.lang.reflect.Method.invoke(Method.java:511)
E/DatabaseUtils(  386):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/DatabaseUtils(  386):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
E/DatabaseUtils(  386):     at dalvik.system.NativeStart.main(Native Method)
D/AndroidRuntime(18537): Shutting down VM
W/dalvikvm(18537): threadid=1: thread exiting with uncaught exception (group=0x42012930)
E/AndroidRuntime(18537): FATAL EXCEPTION: main
E/AndroidRuntime(18537): java.lang.RuntimeException: Unable to start receiver org.fairphone.peaceofmind.PeaceOfMindBroadCastReceiver: java.lang.SecurityException: Permission denial: writing to secure settings requires android.permission.WRITE_SECURE_SETTINGS
E/AndroidRuntime(18537):    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2511)
E/AndroidRuntime(18537):    at android.app.ActivityThread.access$1500(ActivityThread.java:153)
E/AndroidRuntime(18537):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323)
E/AndroidRuntime(18537):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(18537):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(18537):    at android.app.ActivityThread.main(ActivityThread.java:5227)
E/AndroidRuntime(18537):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(18537):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(18537):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/AndroidRuntime(18537):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
E/AndroidRuntime(18537):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(18537): Caused by: java.lang.SecurityException: Permission denial: writing to secure settings requires android.permission.WRITE_SECURE_SETTINGS
E/AndroidRuntime(18537):    at android.os.Parcel.readException(Parcel.java:1425)
E/AndroidRuntime(18537):    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
E/AndroidRuntime(18537):    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
E/AndroidRuntime(18537):    at android.content.ContentProviderProxy.call(ContentProviderNative.java:574)
E/AndroidRuntime(18537):    at android.provider.Settings$NameValueCache.putStringForUser(Settings.java:779)
E/AndroidRuntime(18537):    at android.provider.Settings$Global.putStringForUser(Settings.java:6511)
E/AndroidRuntime(18537):    at android.provider.Settings$Global.putString(Settings.java:6501)
E/AndroidRuntime(18537):    at android.provider.Settings$Global.putInt(Settings.java:6589)
E/AndroidRuntime(18537):    at org.fairphone.peaceofmind.AirplaneModeToggler.setAirplaneModeSettings(AirplaneModeToggler.java:61)
E/AndroidRuntime(18537):    at org.fairphone.peaceofmind.AirplaneModeToggler.setAirplaneModeOn(AirplaneModeToggler.java:38)
E/AndroidRuntime(18537):    at org.fairphone.peaceofmind.AirplaneModeDeviceController.startPeaceOfMind(AirplaneModeDeviceController.java:42)
E/AndroidRuntime(18537):    at org.fairphone.peaceofmind.PeaceOfMindBroadCastReceiver.startPeaceOfMind(PeaceOfMindBroadCastReceiver.java:155)
E/AndroidRuntime(18537):    at org.fairphone.peaceofmind.PeaceOfMindBroadCastReceiver.updateTargetTime(PeaceOfMindBroadCastReceiver.java:188)
E/AndroidRuntime(18537):    at org.fairphone.peaceofmind.PeaceOfMindBroadCastReceiver.onReceive(PeaceOfMindBroadCastReceiver.java:66)
E/AndroidRuntime(18537):    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2504)
E/AndroidRuntime(18537):    ... 10 more
```

Btw do you plan to port the home app to launcher3 soon? That can be built with Android SDK whereas launcher2 cannot. I also see strange Mediatek framework dependencies which I doubt are compatible with the Apache licence and there seems to be no source for fairphonelib.

**Comment by pinkpawkitty** [comment] 2014-01-16 02:25
Which device are you running this on? And are you using an app to limit the permissions of apps?

**Comment by dalb8** [comment] 2014-01-16 10:32
I'm using recent CM10.1 on p990. I don't use a permissions manager though I can't remember if I allowed the app root or not.

**Comment by pinkpawkitty** [comment] 2014-01-16 12:40
You might want to try https://github.com/mudar/Fairphone since this repo 
seems to be for FP1 only.

**Comment by mudar** [comment] 2014-02-04 16:05
I think this issue can be closed as it could be considered as out-of-scope for the original PeaceOfMind.
Error 
`Caused by: java.lang.SecurityException: Permission denial: writing to secure settings requires android.permission.WRITE_SECURE_SETTINGS` means app was not granted root. Airplane mode cannot be set by apps on Android 4.2+ without root access. 
The other solution is for the app to be a system app (which is the case on FP1)

**Comment by kimhansen** [comment] 2014-02-04 16:06
Yes, I agree.

**Closed as completed by kimhansen** 2014-02-04 16:06 UTC
